In [1]:
import numpy as np

In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
print(matrix)
print(matrix[0, 1])
print(matrix @ matrix)
print(matrix.shape)
print(matrix.diagonal())
print(matrix.flatten())
print(matrix.transpose())
print(matrix.min())
print(matrix.max())
print(matrix.mean())
print(matrix.sum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
(3, 3)
[1 5 9]
[1 2 3 4 5 6 7 8 9]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
1
9
5.0
45


In [4]:
my_matrix1 = np.array([[1, 2], [3, 4]])
my_matrix2 = np.array([[2, 0], [1, 2]])
print(my_matrix1 @ my_matrix2)
print(np.vstack([my_matrix1, my_matrix2]))
print(np.hstack([my_matrix1, my_matrix2]))
print(my_matrix1.reshape(1, 4))

[[ 4  4]
 [10  8]]
[[1 2]
 [3 4]
 [2 0]
 [1 2]]
[[1 2 2 0]
 [3 4 1 2]]
[[1 2 3 4]]


In [8]:
# print(np.arange(1, 13).reshape(3, 2, 2))
print(np.arange(1, 24, 2).reshape(3, 2, 2))

[[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]

 [[17 19]
  [21 23]]]


In [24]:
print(np.random.random([3, 3]))

[[0.57393022 0.84880197 0.30327336]
 [0.04291651 0.68740009 0.9340687 ]
 [0.21569788 0.02939022 0.32810754]]
