In [1]:
import numpy as np

In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
print(matrix)
print(matrix[0, 1])
print(matrix @ matrix)
print(matrix.shape)
print(matrix.diagonal())
print(matrix.flatten())
print(matrix.transpose())
print(matrix.min())
print(matrix.max())
print(matrix.mean())
print(matrix.sum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
(3, 3)
[1 5 9]
[1 2 3 4 5 6 7 8 9]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
1
9
5.0
45


In [6]:
my_matrix1 = np.array([[1, 2], [3, 4]])
my_matrix2 = np.array([[2, 0], [1, 2]])
print(my_matrix1 @ my_matrix2)

[[ 4  4]
 [10  8]]
